/**
 * SetupAgent — automates local setup, env validation, DB migration,
 * dev-server launch, Vercel deploy, and self-healing debug cycles.
 *
 * Run directly:  npx tsx src/agents/setupAgent.ts [command]
 * Commands: setup | deploy | debug | status | finetune
 */
import { execSync, spawn } from "child_process";
import * as fs from "fs";
import * as path from "path";
import * as os from "os";

const ROOT = path.resolve(__dirname, "../../");
const ENV_FILE = path.join(ROOT, ".env");
const ENV_EXAMPLE = path.join(ROOT, ".env.example");

// ─── Colour helpers ─────────────────────────────────────────────────────────
const c = {
  reset: "\x1b[0m",
  green: "\x1b[32m",
  yellow: "\x1b[33m",
  red: "\x1b[31m",
  cyan: "\x1b[36m",
  bold: "\x1b[1m",
};
const log = {
  info:    (m: string) => console.log(`${c.cyan}ℹ${c.reset}  ${m}`),
  ok:      (m: string) => console.log(`${c.green}✔${c.reset}  ${m}`),
  warn:    (m: string) => console.log(`${c.yellow}⚠${c.reset}  ${m}`),
  error:   (m: string) => console.log(`${c.red}✖${c.reset}  ${m}`),
  section: (m: string) => console.log(`\n${c.bold}${c.cyan}── ${m} ──${c.reset}`),
};

// ─── REQUIRED VARS ───────────────────────────────────────────────────────────
const REQUIRED: Record<string, string> = {
  DATABASE_URL:     "postgresql://user:password@localhost:5432/builderai",
  ANTHROPIC_API_KEY:"sk-ant-YOUR_KEY_HERE",
  NEXTAUTH_SECRET:  generateSecret(),
  NEXTAUTH_URL:     "http://localhost:3000",
};

const OPTIONAL: Record<string, string> = {
  OPENAI_API_KEY:                    "sk-YOUR_OPENAI_KEY_HERE",
  GITHUB_TOKEN:                      "ghp_YOUR_GITHUB_TOKEN",
  STRIPE_SECRET_KEY:                 "sk_test_YOUR_STRIPE_KEY",
  STRIPE_WEBHOOK_SECRET:             "whsec_YOUR_WEBHOOK_SECRET",
  STRIPE_PRO_MONTHLY_PRICE_ID:       "price_YOUR_PRO_PRICE_ID",
  STRIPE_ENTERPRISE_MONTHLY_PRICE_ID:"price_YOUR_ENTERPRISE_PRICE_ID",
  NEXT_PUBLIC_APP_URL:               "http://localhost:3000",
  NEXT_PUBLIC_APP_NAME:              "BuilderAI",
};

function generateSecret(): string {
  try {
    return execSync("openssl rand -base64 32").toString().trim();
  } catch {
    return Math.random().toString(36).slice(2) + Math.random().toString(36).slice(2);
  }
}

// ─── Step 1: Ensure .env exists ──────────────────────────────────────────────
function ensureEnv(): void {
  log.section("Environment");

  if (!fs.existsSync(ENV_FILE)) {
    log.warn(".env not found — creating from template");

    let content = "# BuilderAI — generated by SetupAgent\n\n";
    content += "# ── REQUIRED ──────────────────────────────────────\n";
    for (const [k, v] of Object.entries(REQUIRED)) {
      content += `${k}="${v}"\n`;
    }
    content += "\n# ── OPTIONAL ──────────────────────────────────────\n";
    for (const [k, v] of Object.entries(OPTIONAL)) {
      content += `# ${k}="${v}"\n`;
    }

    fs.writeFileSync(ENV_FILE, content);
    log.ok(".env created with placeholder values");
  } else {
    log.ok(".env already exists");
  }

  // Load and validate
  const envText = fs.readFileSync(ENV_FILE, "utf8");
  const missing: string[] = [];
  for (const key of Object.keys(REQUIRED)) {
    const hasLine = envText.match(new RegExp(`^${key}=.+`, "m"));
    if (!hasLine) missing.push(key);
  }

  if (missing.length > 0) {
    log.warn(`Missing required env vars: ${missing.join(", ")}`);
    log.warn("Edit .env and fill in real values, then re-run setup.");
  } else {
    log.ok("All required env vars present");
  }
}

// ─── Step 2: Install dependencies ────────────────────────────────────────────
function installDeps(): void {
  log.section("Dependencies");
  try {
    log.info("Running npm install...");
    execSync("npm install", { cwd: ROOT, stdio: "inherit" });
    log.ok("Dependencies installed");
  } catch {
    log.error("npm install failed");
    process.exit(1);
  }
}

// ─── Step 3: Prisma generate + push ──────────────────────────────────────────
function setupDatabase(): void {
  log.section("Database");

  log.info("Generating Prisma client...");
  try {
    execSync("npx prisma generate", { cwd: ROOT, stdio: "inherit" });
    log.ok("Prisma client generated");
  } catch {
    log.error("prisma generate failed");
    process.exit(1);
  }

  log.info("Pushing schema to database (npx prisma db push)...");
  try {
    execSync("npx prisma db push --accept-data-loss", { cwd: ROOT, stdio: "inherit" });
    log.ok("Database schema synced");
  } catch (e) {
    log.warn("prisma db push failed — check DATABASE_URL in .env");
    log.warn("Continuing anyway (app will run in degraded mode without DB)");
  }
}

// ─── Step 4: Start dev server ─────────────────────────────────────────────────
function startDev(): void {
  log.section("Dev Server");

  const port = process.env.PORT ?? "3000";
  log.info(`Starting Next.js on http://localhost:${port} ...`);
  log.info("Press Ctrl+C to stop\n");

  const child = spawn("npm", ["run", "dev"], {
    cwd: ROOT,
    stdio: "inherit",
    env: { ...process.env, PORT: port },
    shell: true,
  });

  child.on("error", (err) => { log.error(`Dev server error: ${err.message}`); });
  child.on("exit", (code) => {
    if (code !== 0) log.error(`Dev server exited with code ${code}`);
  });

  process.on("SIGINT",  () => { child.kill("SIGINT");  process.exit(0); });
  process.on("SIGTERM", () => { child.kill("SIGTERM"); process.exit(0); });
}

// ─── Step 5: Production build ─────────────────────────────────────────────────
function buildProd(): void {
  log.section("Production Build");
  try {
    execSync("npx prisma generate && npm run build", { cwd: ROOT, stdio: "inherit", shell: "/bin/sh" });
    log.ok("Build succeeded");
  } catch {
    log.error("Build failed — run debug command to diagnose");
    process.exit(1);
  }
}

// ─── Deploy via Vercel CLI ────────────────────────────────────────────────────
function deployVercel(prod = false): void {
  log.section("Vercel Deploy");

  // Check if vercel CLI is available
  try { execSync("vercel --version", { stdio: "pipe" }); }
  catch {
    log.info("Installing Vercel CLI...");
    execSync("npm install -g vercel", { stdio: "inherit" });
  }

  const flag = prod ? "--prod" : "";
  log.info(`Deploying to Vercel ${prod ? "(production)" : "(preview)"}...`);
  try {
    execSync(`vercel ${flag} --yes`, { cwd: ROOT, stdio: "inherit", shell: "/bin/sh" });
    log.ok("Deployed! Check your Vercel dashboard for the URL.");
    log.info("Your placeholder domain: https://YOUR-PROJECT.vercel.app");
    log.info("Add a custom domain any time: vercel domains add yourdomain.com");
  } catch {
    log.error("Vercel deploy failed.");
    log.info("Make sure you are logged in: vercel login");
    log.info("Then re-run: npx tsx src/agents/setupAgent.ts deploy");
  }
}

// ─── Debug: type-check + lint + build diagnostics ────────────────────────────
function debugApp(): void {
  log.section("Debug & Diagnostics");
  let passed = 0; let failed = 0;

  const run = (label: string, cmd: string) => {
    log.info(`Checking: ${label}...`);
    try {
      execSync(cmd, { cwd: ROOT, stdio: "pipe" });
      log.ok(label); passed++;
    } catch (e) {
      const out = e instanceof Error && "stdout" in e
        ? (e as NodeJS.ErrnoException & {stdout:Buffer}).stdout?.toString()
        : String(e);
      log.error(`${label} FAILED`);
      console.log(out?.slice(0, 800));
      failed++;
    }
  };

  run("TypeScript", "npx tsc --noEmit");
  run("Next.js build", "npx prisma generate && npm run build");
  run("Env vars",  `node -e "require('dotenv').config(); const m=['DATABASE_URL','ANTHROPIC_API_KEY','NEXTAUTH_SECRET'].filter(k=>!process.env[k]); if(m.length) throw new Error('Missing: '+m)"`);

  log.section("Summary");
  log.ok(`Passed: ${passed}`);
  if (failed > 0) log.error(`Failed: ${failed} — fix the issues above then re-run`);
  else log.ok("All checks passed — app is healthy");
}

// ─── Fine-tune: set optimal Next.js + Node config ─────────────────────────────
function finetune(): void {
  log.section("Fine-Tune");

  // 1. Check Node version
  const nodeVer = process.version;
  log.info(`Node.js: ${nodeVer}`);
  const major = parseInt(nodeVer.slice(1));
  if (major < 18) {
    log.warn("Upgrade to Node 18+ for best performance");
  } else {
    log.ok("Node.js version OK");
  }

  // 2. Ensure .nvmrc
  const nvmrc = path.join(ROOT, ".nvmrc");
  if (!fs.existsSync(nvmrc)) {
    fs.writeFileSync(nvmrc, "20\n");
    log.ok("Created .nvmrc (Node 20)");
  }

  // 3. Ensure robots.txt for domain searchability
  const publicDir = path.join(ROOT, "public");
  if (!fs.existsSync(publicDir)) fs.mkdirSync(publicDir);
  const robots = path.join(publicDir, "robots.txt");
  if (!fs.existsSync(robots)) {
    fs.writeFileSync(robots, [
      "User-agent: *",
      "Allow: /",
      "Disallow: /api/",
      "Disallow: /dashboard",
      "Disallow: /projects",
      "Disallow: /settings",
      "",
      "# Sitemap: https://YOUR-DOMAIN.com/sitemap.xml",
    ].join("\n"));
    log.ok("Created public/robots.txt (search-engine ready)");
  }

  // 4. Sitemap placeholder
  const sitemap = path.join(publicDir, "sitemap.xml");
  if (!fs.existsSync(sitemap)) {
    const url = process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000";
    fs.writeFileSync(sitemap, `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url><loc>${url}/</loc><changefreq>weekly</changefreq><priority>1.0</priority></url>
  <url><loc>${url}/login</loc><changefreq>monthly</changefreq><priority>0.5</priority></url>
  <url><loc>${url}/register</loc><changefreq>monthly</changefreq><priority>0.8</priority></url>
</urlset>`);
    log.ok("Created public/sitemap.xml");
  }

  // 5. Performance hints
  log.section("Performance Tips");
  log.info("1. Set DATABASE_URL to a pooled connection (PgBouncer / Supabase pooler)");
  log.info("2. Enable Vercel Analytics: vercel env add VERCEL_ANALYTICS_ID");
  log.info("3. Add Redis for BullMQ job queue when > 10 concurrent builds");
  log.info("4. Set NEXT_PUBLIC_APP_URL to your production domain");
  log.info("5. Run: vercel domains add yourdomain.com  (when you buy a domain)");

  log.ok("Fine-tune complete");
}

// ─── Status check ──────────────────────────────────────────────────────────
function status(): void {
  log.section("Status");

  const checks = [
    { label: "package.json",     ok: fs.existsSync(path.join(ROOT, "package.json")) },
    { label: ".env",             ok: fs.existsSync(ENV_FILE) },
    { label: "prisma/schema",    ok: fs.existsSync(path.join(ROOT, "prisma/schema.prisma")) },
    { label: "node_modules",     ok: fs.existsSync(path.join(ROOT, "node_modules")) },
    { label: "Prisma client",    ok: fs.existsSync(path.join(ROOT, "node_modules/@prisma/client")) },
    { label: ".next build",      ok: fs.existsSync(path.join(ROOT, ".next")) },
    { label: "public/robots.txt",ok: fs.existsSync(path.join(ROOT, "public/robots.txt")) },
  ];

  for (const c2 of checks) {
    if (c2.ok) log.ok(c2.label);
    else        log.warn(`${c2.label} — not found`);
  }

  const envText = fs.existsSync(ENV_FILE) ? fs.readFileSync(ENV_FILE, "utf8") : "";
  log.section("Env var status");
  for (const key of [...Object.keys(REQUIRED), ...Object.keys(OPTIONAL)]) {
    const present = envText.match(new RegExp(`^${key}=.+`, "m"));
    if (present) log.ok(key);
    else         log.warn(`${key} — not set`);
  }
}

// ─── CLI entry ────────────────────────────────────────────────────────────────
async function main() {
  const cmd = process.argv[2] ?? "setup";
  console.log(`\n${c.bold}${c.cyan}⚡ BuilderAI SetupAgent${c.reset} — command: ${cmd}\n`);

  switch (cmd) {
    case "setup":
      ensureEnv();
      installDeps();
      setupDatabase();
      finetune();
      log.section("Ready");
      log.ok("Setup complete! Run: npx tsx src/agents/setupAgent.ts run");
      break;

    case "run":
      ensureEnv();
      setupDatabase();
      startDev();
      break;

    case "build":
      ensureEnv();
      setupDatabase();
      buildProd();
      break;

    case "deploy":
      ensureEnv();
      buildProd();
      deployVercel(process.argv[3] === "--prod");
      break;

    case "debug":
      debugApp();
      break;

    case "finetune":
      finetune();
      break;

    case "status":
      status();
      break;

    default:
      console.log(`
Usage: npx tsx src/agents/setupAgent.ts <command>

Commands:
  setup      Create .env, install deps, push DB schema, fine-tune (first run)
  run        Start the development server (http://localhost:3000)
  build      Production build
  deploy     Deploy to Vercel preview (add --prod for production)
  debug      TypeScript check + build diagnostics
  finetune   Optimise config, create robots.txt + sitemap
  status     Show health of all required files and env vars
`);
  }
}

main().catch((e) => { log.error(String(e)); process.exit(1); });
